use Tagcloud;

insert into Keyword (id, word) value (1, "Morfologia Matemática");
insert into Keyword (id, word) value (2, "Processamento de Imagens");
insert into Keyword (id, word) value (3, "Fotogrametria");
insert into Keyword (id, word) value (4, "Bit-stream");
insert into Keyword (id, word) value (5, "Comunicação Serial");
insert into Keyword (id, word) value (6, "Panorama 360");
insert into Keyword (id, word) value (7, "SIFT");
insert into Keyword (id, word) value (8, "RANSAC");
insert into Keyword (id, word) value (9, "Automação");
insert into Keyword (id, word) value (10, "Inteligência Artificial");
insert into Keyword (id, word) value (11, "Algoritmos Genéticos");
insert into Keyword (id, word) value (12, "Calibração de Câmeras");
insert into Keyword (id, word) value (13, "Alvos Codificados");
insert into Keyword (id, word) value (14, "Precisão Sub-Pixel");
insert into Keyword (id, word) value (15, "ARUCO");
insert into Keyword (id, word) value (16, "OpenCV");
insert into Keyword (id, word) value (17, "Controle de Tráfego");
insert into Keyword (id, word) value (18, "Smartphone");
insert into Keyword (id, word) value (19, "GPS");
insert into Keyword (id, word) value (20, "Visão Computacional");
insert into Keyword (id, word) value (21, "Características Locais");
insert into Keyword (id, word) value (22, "Detector de Pontos Chave");
insert into Keyword (id, word) value (23, "Descritor de Pontos Chave");
insert into Keyword (id, word) value (24, "Extração de Feições");
insert into Keyword (id, word) value (25, "Varredura a Laser");
insert into Keyword (id, word) value (26, "Contorno de Telhados");
insert into Keyword (id, word) value (27, "Reconhecimento de Padrões");
insert into Keyword (id, word) value (28, "Redes Neurais");
insert into Keyword (id, word) value (29, "Sistema OCR");
insert into Keyword (id, word) value (30, "Tempo Real");
insert into Keyword (id, word) value (31, "Detecção de Sinais de Trânsito");
insert into Keyword (id, word) value (32, "Fecho Convexo");
insert into Keyword (id, word) value (33, "Interface Homem-Computador");
insert into Keyword (id, word) value (34, "Modelo HSV");
insert into Keyword (id, word) value (35, "Modelo YCrCb");
insert into Keyword (id, word) value (36, "Super-Resolution Image");
insert into Keyword (id, word) value (37, "Computação Gráfica");
insert into Keyword (id, word) value (38, "Reconstrução 3D");
insert into Keyword (id, word) value (39, "Imagens Raio-X");
insert into Keyword (id, word) value (40, "Reconhecimento de Caracteres Manuscritos");
insert into Keyword (id, word) value (41, "Efeitos Especiais");
insert into Keyword (id, word) value (42, "Morphing");
insert into Keyword (id, word) value (43, "Fisiologia de Plantas");
insert into Keyword (id, word) value (44, "Visualização de Informações");
insert into Keyword (id, word) value (45, "Análise de Dados");
insert into Keyword (id, word) value (46, "Código de Barras");
insert into Keyword (id, word) value (47, "Microcontrolador");
insert into Keyword (id, word) value (48, "Rádio Frequência");
insert into Keyword (id, word) value (49, "XSL");
insert into Keyword (id, word) value (50, "PDF");
insert into Keyword (id, word) value (51, "XML");
insert into Keyword (id, word) value (52, "Mineração de Textos");
insert into Keyword (id, word) value (53, "Processamento de Linguagem Natural");
insert into Keyword (id, word) value (54, "Stemmer");
insert into Keyword (id, word) value (55, "Stopwords");
insert into Keyword (id, word) value (56, "Segmentação");
insert into Keyword (id, word) value (57, "Detecção adaptativa de bordas");
insert into Keyword (id, word) value (58, "Afinamento");
insert into Keyword (id, word) value (59, "Processamento de Vídeo");
insert into Keyword (id, word) value (60, "Lousa Eletrônica");
insert into Keyword (id, word) value (61, "Ensino à Distância");
insert into Keyword (id, word) value (62, "Viz3D");
insert into Keyword (id, word) value (63, "Coordenadas Paralelas");
insert into Keyword (id, word) value (64, "Técnica Varredura e Rotulação");
insert into Keyword (id, word) value (65, "Detecção Automática de Linhas Retas");
insert into Keyword (id, word) value (66, "Análise Geométrica");
insert into Keyword (id, word) value (67, "Tradução de Textos");
insert into Keyword (id, word) value (68, "Android");
insert into Keyword (id, word) value (69, "Extração de Textos de Imagens");
insert into Keyword (id, word) value (70, "Licence Plate Recognition");
insert into Keyword (id, word) value (71, "Social Spider Optimization");
insert into Keyword (id, word) value (72, "Optical Flow");
insert into Keyword (id, word) value (73, "Evolutionary Optimization Methods");
insert into Keyword (id, word) value (74, "Reconhecimento de Faces");
insert into Keyword (id, word) value (75, "Segurança");
insert into Keyword (id, word) value (76, "AdaBoost");
insert into Keyword (id, word) value (77, "Reconhecimento de Notas Musicais");
insert into Keyword (id, word) value (78, "Reconhecimento de Objetos");
insert into Keyword (id, word) value (79, "Detecção de Faces");
insert into Keyword (id, word) value (80, "Aproximação de Tom de Pele");
insert into Keyword (id, word) value (81, "Transformada de Hough");
insert into Keyword (id, word) value (82, "Filtro de Canny");
