use Tagcloud;

insert into Publicacao_Keyword (idPublicacao, idKeyword) value (1, 1);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (1, 2);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (1, 3);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (1, 4);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (1, 5);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (2, 2);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (2, 6);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (2, 7);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (2, 8);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (3, 9);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (3, 1);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (3, 10);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (3, 11);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (4, 12);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (4, 13);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (4, 14);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (4, 3);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (4, 15);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (4, 16);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (5, 17);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (5, 18);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (5, 19);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (6, 20);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (6, 21);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (6, 22);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (6, 23);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (6, 7);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (7, 24);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (7, 25);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (7, 26);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (7, 20);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (8, 2);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (8, 10);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (8, 20);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (8, 27);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (8, 28);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (8, 29);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (9, 2);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (9, 20);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (9, 30);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (9, 31);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (9, 34);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (10, 2);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (10, 7);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (10, 20);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (10, 29);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (11, 32);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (11, 33);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (11, 20);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (11, 34);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (11, 35);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (12, 6);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (12, 7);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (12, 8);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (12, 16);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (12, 2);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (13, 36);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (13, 20);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (13, 7);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (13, 8);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (13, 2);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (13, 29);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (14, 37);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (14, 38);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (14, 39);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (15, 40);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (15, 2);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (15, 20);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (15, 29);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (15, 28);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (16, 37);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (16, 41);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (16, 42);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (17, 28);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (17, 43);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (17, 44);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (17, 45);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (18, 46);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (18, 47);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (18, 48);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (19, 49);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (19, 50);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (19, 51);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (19, 52);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (19, 53);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (19, 54);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (19, 55);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (20, 56);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (20, 57);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (20, 58);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (21, 59);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (21, 60);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (21, 61);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (22, 37);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (22, 44);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (22, 45);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (22, 62);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (22, 63);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (23, 2);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (23, 3);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (23, 56);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (23, 64);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (24, 2);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (24, 3);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (24, 24);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (24, 56);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (24, 65);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (27, 12);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (27, 13);
insert into Publicacao_Keyword (idPublicacao, idKeyword) value (27, 15);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (28, 17);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (28, 27);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (28, 66);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (30, 2);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (30, 20);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (30, 67);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (30, 68);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (30, 69);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (31, 1);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (31, 29);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (31, 70);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (32, 71);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (32, 72);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (32, 73);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (33, 20);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (33, 68);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (33, 74);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (33, 75);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (34, 7);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (34, 31);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (34, 76);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (34, 22);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (34, 34);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (35, 1);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (35, 20);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (35, 77);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (35, 56);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (36, 7);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (36, 21);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (36, 22);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (36, 23);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (36, 78);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (37, 79);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (37, 80);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (37, 81);
-- insert into Publicacao_Keyword (idPublicacao, idKeyword) value (37, 82);
