use Tagcloud;

insert into Keyword (id, word) value (1, "Morfologia Matemática");
insert into Keyword (id, word) value (2, "Processamento de Imagens");
insert into Keyword (id, word) value (3, "Fotogrametria");
insert into Keyword (id, word) value (4, "Bit-stream");
insert into Keyword (id, word) value (5, "Comunicação Serial");
insert into Keyword (id, word) value (6, "Panorama 360");
insert into Keyword (id, word) value (7, "SIFT");
insert into Keyword (id, word) value (8, "RANSAC");
insert into Keyword (id, word) value (9, "Automação");
insert into Keyword (id, word) value (10, "Inteligência Artificial");
insert into Keyword (id, word) value (11, "Algoritmos Genéticos");
insert into Keyword (id, word) value (12, "Calibração de Câmeras");
insert into Keyword (id, word) value (13, "Alvos Codificados");
insert into Keyword (id, word) value (14, "Precisão Sub-Pixel");
insert into Keyword (id, word) value (15, "ARUCO");
insert into Keyword (id, word) value (16, "OpenCV");
insert into Keyword (id, word) value (17, "Controle de Tráfego");
insert into Keyword (id, word) value (18, "Smartphone");
insert into Keyword (id, word) value (19, "GPS");
insert into Keyword (id, word) value (20, "Visão Computacional");
insert into Keyword (id, word) value (21, "Características Locais");
insert into Keyword (id, word) value (22, "Detector de Pontos Chave");
insert into Keyword (id, word) value (23, "Descritor de Pontos Chave");
insert into Keyword (id, word) value (24, "Extração de Feições");
insert into Keyword (id, word) value (25, "Varredura a Laser");
insert into Keyword (id, word) value (26, "Contorno de Telhados");
insert into Keyword (id, word) value (27, "Reconhecimento de Padrões");
insert into Keyword (id, word) value (28, "Redes Neurais");
insert into Keyword (id, word) value (29, "Sistema OCR");
insert into Keyword (id, word) value (30, "Tempo Real");
insert into Keyword (id, word) value (31, "Detecção de Sinais de Trânsito");
insert into Keyword (id, word) value (32, "Fecho Convexo");
insert into Keyword (id, word) value (33, "Interface Homem-Computador");
insert into Keyword (id, word) value (34, "Modelo HSV");
insert into Keyword (id, word) value (35, "Modelo YCrCb");
insert into Keyword (id, word) value (36, "Super-Resolution Image");
insert into Keyword (id, word) value (37, "Computação Gráfica");
insert into Keyword (id, word) value (38, "Reconstrução 3D");
insert into Keyword (id, word) value (39, "Imagens Raio-X");
insert into Keyword (id, word) value (40, "Reconhecimento de Caracteres Manuscritos");
insert into Keyword (id, word) value (41, "Efeitos Especiais");
insert into Keyword (id, word) value (42, "Morphing");
insert into Keyword (id, word) value (43, "Fisiologia de Plantas");
insert into Keyword (id, word) value (44, "Visualização de Informações");
insert into Keyword (id, word) value (45, "Análise de Dados");
insert into Keyword (id, word) value (46, "Código de Barras");
insert into Keyword (id, word) value (47, "Microcontrolador");
insert into Keyword (id, word) value (48, "Rádio Frequência");
insert into Keyword (id, word) value (49, "XSL");
insert into Keyword (id, word) value (50, "PDF");
insert into Keyword (id, word) value (51, "XML");
insert into Keyword (id, word) value (52, "Mineração de Textos");
insert into Keyword (id, word) value (53, "Processamento de Linguagem Natural");
insert into Keyword (id, word) value (54, "Stemmer");
insert into Keyword (id, word) value (55, "Stopwords");
insert into Keyword (id, word) value (56, "Segmentação");
insert into Keyword (id, word) value (57, "Detecção adaptativa de bordas");
insert into Keyword (id, word) value (58, "Afinamento");
insert into Keyword (id, word) value (59, "Processamento de Vídeo");
insert into Keyword (id, word) value (60, "Lousa Eletrônica");
insert into Keyword (id, word) value (61, "Ensino à Distância");
insert into Keyword (id, word) value (62, "Viz3D");
insert into Keyword (id, word) value (63, "Coordenadas Paralelas");
insert into Keyword (id, word) value (64, "Técnica Varredura e Rotulação");
insert into Keyword (id, word) value (65, "Detecção Automática de Linhas Retas");
insert into Keyword (id, word) value (66, "Análise Geométrica");
insert into Keyword (id, word) value (67, "Tradução de Textos");
insert into Keyword (id, word) value (68, "Android");
insert into Keyword (id, word) value (69, "Extração de Textos de Imagens");
insert into Keyword (id, word) value (70, "Licence Plate Recognition");
insert into Keyword (id, word) value (71, "Social Spider Optimization");
insert into Keyword (id, word) value (72, "Optical Flow");
insert into Keyword (id, word) value (73, "Evolutionary Optimization Methods");
insert into Keyword (id, word) value (74, "Reconhecimento de Faces");
insert into Keyword (id, word) value (75, "Segurança");
insert into Keyword (id, word) value (76, "AdaBoost");
insert into Keyword (id, word) value (77, "Reconhecimento de Notas Musicais");
insert into Keyword (id, word) value (78, "Reconhecimento de Objetos");
insert into Keyword (id, word) value (79, "Detecção de Faces");
insert into Keyword (id, word) value (80, "Aproximação de Tom de Pele");
insert into Keyword (id, word) value (81, "Transformada de Hough");
insert into Keyword (id, word) value (82, "Filtro de Canny");
insert into Keyword (id, word) value (83, "Backpropagation Neural Network");
insert into Keyword (id, word) value (84, "Image Rectification");
insert into Keyword (id, word) value (85, "Image Adjustment");
insert into Keyword (id, word) value (86, "Google Earth");
insert into Keyword (id, word) value (87, "Blend Algorithm");
insert into Keyword (id, word) value (88, "Modelagem 3D de ossos");
insert into Keyword (id, word) value (89, "Free Form Deformation");
insert into Keyword (id, word) value (90, "Mobile Mapping System");
insert into Keyword (id, word) value (91, "BBF Algorithm");
insert into Keyword (id, word) value (92, "Reconhecimento de Gestos");
insert into Keyword (id, word) value (93, "Barcode");
insert into Keyword (id, word) value (94, "Visualização Multidimensional");
insert into Keyword (id, word) value (95, "Dimension Reduction");
insert into Keyword (id, word) value (96, "Visual Clustering");
insert into Keyword (id, word) value (97, "Density-Based Visualization");
insert into Keyword (id, word) value (98, "Visual Data-mining");
insert into Keyword (id, word) value (99, "Realidade Virtual");
insert into Keyword (id, word) value (100, "VRML");
insert into Keyword (id, word) value (101, "Estudo do Lançamento de Projéteis");
insert into Keyword (id, word) value (102, "Lâmpada Estroboscópica");
insert into Keyword (id, word) value (103, "Estimação da Idade Óssea");
insert into Keyword (id, word) value (104, "Greulich & Pyle");
insert into Keyword (id, word) value (105, "Tanner & Whitehouse");
insert into Keyword (id, word) value (106, "Eklof & Ringertz");
insert into Keyword (id, word) value (107, "Imagens Médicas");
insert into Keyword (id, word) value (108, "Radiografia Carpal");
insert into Keyword (id, word) value (109, "Artificial Neural Network");
insert into Keyword (id, word) value (110, "Anacarp");
insert into Keyword (id, word) value (111, "Banco de Dados");
insert into Keyword (id, word) value (112, "Data Synchronization");
insert into Keyword (id, word) value (113, "MySQLite");
insert into Keyword (id, word) value (114, "Anycast");
insert into Keyword (id, word) value (115, "Sistemas Distribuídos");
insert into Keyword (id, word) value (116, "Escalabilidade");
insert into Keyword (id, word) value (117, "AVDNet");
insert into Keyword (id, word) value (118, "Engenharia de Software");
insert into Keyword (id, word) value (119, "Lab Packages");
insert into Keyword (id, word) value (120, "Controlled Experiments");
insert into Keyword (id, word) value (121, "Estrutura de Dados");
insert into Keyword (id, word) value (122, "Feramenta de Aprendizado");
insert into Keyword (id, word) value (123, "Cadilag");
insert into Keyword (id, word) value (124, "Ferramenta Visual");
insert into Keyword (id, word) value (125, "Plataforma Web");
insert into Keyword (id, word) value (126, "Grafos");
insert into Keyword (id, word) value (127, "HTML & CSS & JS");
insert into Keyword (id, word) value (128, "MySQL");
insert into Keyword (id, word) value (129, "AJAX");
insert into Keyword (id, word) value (130, "AnyAVDNet");
insert into Keyword (id, word) value (131, "Ambiente Virtual Distribuído");
insert into Keyword (id, word) value (132, "Número de Ouro");
insert into Keyword (id, word) value (133, "Snakes");
insert into Keyword (id, word) value (134, "Contornos Ativos");
insert into Keyword (id, word) value (135, "Método da Assinatura Vertical");
insert into Keyword (id, word) value (136, "Previsão Hidrometeorológica");
insert into Keyword (id, word) value (137, "Efeito Heel");
insert into Keyword (id, word) value (138, "Algoritmos de Thresholding");
insert into Keyword (id, word) value (139, "Código Paralelo");
insert into Keyword (id, word) value (140, "PVM");
insert into Keyword (id, word) value (141, "Super-exposição ao computador");
insert into Keyword (id, word) value (142, "Interface Gráfica");
insert into Keyword (id, word) value (143, "Aplicação para Linux");
insert into Keyword (id, word) value (144, "Aplicação para Windows");
insert into Keyword (id, word) value (145, "Fiber Tracts");
insert into Keyword (id, word) value (146, "Interactive Data Exploration");
insert into Keyword (id, word) value (147, "Piecewise Laplacian-based Projection");
insert into Keyword (id, word) value (148, "PEx-Image");
insert into Keyword (id, word) value (149, "Recuperação de Imagens");
insert into Keyword (id, word) value (150, "Coordinated Multiple Views");
insert into Keyword (id, word) value (151, "Coordination Techniques");
insert into Keyword (id, word) value (152, "Multimodal Dataset");
insert into Keyword (id, word) value (153, "Linked Views");
insert into Keyword (id, word) value (154, "Multi-projeção");
