use Tagcloud;

insert into Publicacao (id, titulo, referencia) value (1, "A Bit-Stream Morphological Image Processing Method for Planetary Images", "Boletim de Ciências Geodésicas, v. 20, p. 626-646, 2014.");
insert into Publicacao (id, titulo, referencia) value (2, "StitchingPHm - A New Algorithm for Panoramic Images", "Pattern Recognition and Image Analysis, v. 24, p. 41-56, 2014.");
insert into Publicacao (id, titulo, referencia) value (3, "Mathematical Morphology and Artificial Intelligence Applied to Help Golf-Balls Collecting in Driving Ranges.", "International Journal of Applied Mathematics, v. 27, p. 73-88, 2014.");
insert into Publicacao (id, titulo, referencia) value (4, "Utilização de Alvos Codificados do Tipo Aruco na Automação do Processo de Calibração de Câmaras.", "Boletim de Ciências Geodésicas, v. 20, p. 626-646, 2014.");
insert into Publicacao (id, titulo, referencia) value (5, "Compartilhamento de Informações de Trânsito Utilizando Smartphones.", "Colloquium Exactarum, v. 6, p. 16-35, 2014.");
insert into Publicacao (id, titulo, referencia) value (6, "Detecção e Reconhecimento de Objetos em Imagens Utilizando Algoritmos de Extração de Pontos Chave.", "Colloquium Exactarum, v. 6, p. 86-103, 2014.");
insert into Publicacao (id, titulo, referencia) value (7, "Extração de Contorno de Telhados de Edificações Utilizando Dados Laser e Imagens Aéreas.", "Colloquium Exactarum, v. 6, p. 104-119, 2014.");
insert into Publicacao (id, titulo, referencia) value (8, "Redes Neurais Classe Modular Aplicadas no Reconhecimento de Caracteres Manuscritos.", "Colloquium Exactarum, v. 6, p. 170-183, 2014.");
insert into Publicacao (id, titulo, referencia) value (9, "Uma Metodologia para Detecção de Sinais de Trânsito em Vídeo", "Colloquium Exactarum, v. 6, p. 26-44, 2014.");
insert into Publicacao (id, titulo, referencia) value (10, "A New Approach for License Plate Recognition Using the SIFT Algorithm. Signal & Image Processing", "An International Journal, v. 4, p. 17-33, 2013.");
insert into Publicacao (id, titulo, referencia) value (11, "Reconhecimento de Objetos Coloridos e Mãos Usando Cores e Formas", "Colloquium Exactarum, v. 5, p. 01-11, 2013.");
insert into Publicacao (id, titulo, referencia) value (12, "Algoritmos para Construção de Panorama de Imagens 360 e Visualização", "Colloquium Exactarum, v. 5, p. 12-25, 2013.");
insert into Publicacao (id, titulo, referencia) value (13, "Super-Resolution Images Enhanced for Applications to Character Recognition", "The SIJ Transactions on Computer Science Engineering & its Applications(CSEA),v.1,p.67-74,2013.");
insert into Publicacao (id, titulo, referencia) value (14, "Reconstrução 3D de Ossos a partir de Imagens de Raio-X", "Colloquium Exactarum, v. 5, p. 87-108, 2013.");
insert into Publicacao (id, titulo, referencia) value (15, "Algoritmo para o Reconhecimento de Caracteres Manuscritos", "Colloquium Exactarum, v. 5, p. 109-127, 2013.");
insert into Publicacao (id, titulo, referencia) value (16, "Efeitos Especiais em Computação Gráfica – Morphing", "Colloquium Exactarum, v. 03, p. 85-92, 2011.");
insert into Publicacao (id, titulo, referencia) value (17, "ANÁLISE DE DADOS DE FISIOLOGIA DE PLANTAS APOIADA POR TÉCNICAS DE VISUALIZAÇÃO DE INFORMAÇÕES.", "Colloquium Exactarum, v. 03, p. 114-123, 2011.");
insert into Publicacao (id, titulo, referencia) value (18, "Transmissão de Código de Barras por Rádio Frequência usando Microcontroladores.", "Colloquium Exactarum, v. 02, p. 20-31, 2010.");
insert into Publicacao (id, titulo, referencia) value (19, "Ferramenta de Busca para Redação Jornalística.", "Colloquium Exactarum, v. 02, p. 83-91, 2010.");
insert into Publicacao (id, titulo, referencia) value (20, "DETECÇÃO E AFINAMENTO DE BORDAS EM DIREÇÕES PREVIAMENTE CONHECIDAS.", "Boletim de Ciências Geodésicas, v. 15, p. 157-177, 2009.");
insert into Publicacao (id, titulo, referencia) value (21, "E-LOUSA - UMA LOUSA ELETRÔNICA BASEADA EM ANÁLISE DE IMAGENS.", "Colloquium Exactarum, v. 1, p. 9-21, 2009.");
insert into Publicacao (id, titulo, referencia) value (22, "Visualização exploratória de parâmetros de eletromiografia relevantes para diferenciar contrações isométricas.", "Revista Brasileira de Biomecânica (Impresso), v. 8, p. 74-81, 2007.");
insert into Publicacao (id, titulo, referencia) value (23, "Um Método para a Conexão e Aproximação Poligonal de Elementos de Bordas em Imagens Digitais.", "Boletim de Ciências Geodésicas (Impresso), Curitiba-PR, v. 8, p. 71-94, 2002.");
insert into Publicacao (id, titulo, referencia) value (24, "Extração de Feições Retas em Imagens Digitais: Adaptação e Avaliação de Diferentes Técnicas.", "Geodésia OnLine, Florianópolis-SC, v. 2, n.1, p. 1-23, 2002.");
insert into Publicacao (id, titulo, referencia) value (25, "Limiarização Automática de Imagens Digitais.", "Boletim de Ciências Geodésicas, CURITIBA, v. 6, n.1, p. 38-48, 2000.");
insert into Publicacao (id, titulo, referencia) value (26, "Transformações Espaciais e Técnicas de Interpolação Aplicadas em Imagens.", "Colloquium, PRESIDENTE PRUDENTE, v. 1, n.3, p. 43-51, 1998.");
insert into Publicacao (id, titulo, referencia) value (27, "Calibration of Panoramic Cameras with Coded Targets and a 3D Calibration Field.", "In: EuroCOW 2014 - the European Calibration and Orientation Workshop, 2014, Castelldefels, Espanha.");
